Feature/slider пример компонента
avdotion/clue pull request #37
Opened 2020-03-05 13:10 UTC by killreal17

Написал пример компонента из Pitaya с документацией

2020-03-08 15:50 UTC, avdotion commented on src/components/Slider/README.mdx
> +---
Документацию можно, к сожалению, выпилить.

2020-03-08 15:50 UTC, avdotion commented on src/components/Slider/index.tsx
> +// @ts-ignore
Давай не будем никогда игнорировать проверки TS

2020-03-08 15:51 UTC, avdotion commented on src/components/Slider/index.tsx
> +      font-family: Roboto Mono;
Знание о шрифте вынесено в рутовый компонент

2020-03-08 15:52 UTC, avdotion commented on src/components/Slider/index.tsx
> +ref: any) => styled(
Давай попробуем избавиться от `any` в типах?

2020-03-08 15:53 UTC, avdotion commented on src/components/Slider/index.tsx
> +    as='div'
И без того по дефолту будет `div`

2020-03-08 15:54 UTC, avdotion commented on src/components/Slider/index.tsx
> +    left: ${offsetLeft};
Вместо `left` используй трансформацию.
К сожалению, анимации в 60 fps и более невозможно добиться с абсолютным позиционированием.

2020-03-08 15:55 UTC, avdotion commented on src/components/Slider/index.tsx
> +
Зачем эта пустая строчка?

2020-03-08 15:56 UTC, avdotion commented on src/components/Slider/index.tsx
> +      .current[options.indexOf(currentOption)]
Выглядит нечитаемо. Кроме того, ты пытаешь обратиться к рефу, который может быть null.

2020-03-08 15:58 UTC, avdotion commented on src/components/Slider/index.tsx
> +          ref={option => optionRefs.current[index] = option}
Лучше вынести лямбду в константу, assignment возвращает undefined, но лучше обворачивать такие выражения в фигурные скобки

2020-03-08 15:58 UTC, avdotion requested changes
Есть несколько замечаний. Предлагаю вернуться к решению этой задачи после выкатки компонентов Typo, Root и Grid.

2020-03-09 14:08 UTC, killreal17 commented on src/components/Slider/index.tsx
> +// @ts-ignore
В данном случае это было связанно с docz

2020-09-04 11:47 UTC, closed without merging