#57 Написал компонент отвечающий за поля ввода
avdotion/clue pull request #59
Opened 2020-04-17 19:08 UTC by killreal17

Написал компонент, отвечающий за поля ввода. 
Сам компонент включает в себя заголовок, добавочную строку (напр. 'https://'), поле для ввода и место для кастомной кнопки.
Кастомную кнопку требуется прописывать отдельным компонентом.

2020-04-23 17:02 UTC, avdotion commented on src/components/Input.tsx
> +    cursor: pointer;
Зачем это было сделано?

2020-04-25 22:32 UTC, avdotion commented on src/pitaya/components/Text/index.tsx
> +|text {
Верни, пожалуйста, индентацию.

2020-04-25 22:33 UTC, avdotion commented on src/pitaya/components/Text/index.tsx
> +|text[use|theme='heading'] {
Синтаксический  сахар не сработал? Зачем это было сделано?

2020-04-25 22:35 UTC, avdotion commented on src/pitaya/components/Text/index.tsx
> +  font-weight: 400;
У нас нет этой толщины для Roboto Mono, нужно добавить, чтобы стили сошлись.

2020-04-25 22:36 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +    padding: 0 20px 0;
```suggestion
    padding: 0 20px;
```

2020-04-25 22:36 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +  |wrapper {
```suggestion
export const inputStyles = css`
  |wrapper {
```

2020-04-25 22:38 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +    border: 1px solid black;
Нужно вынести цвет отдельно в константу, чтобы потом на темную тему бесплатно перейти.

2020-04-25 22:39 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +  }
```suggestion
  input:required, input:invalid {
    box-shadow: none;
  }
```

2020-04-25 22:41 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +    font-family: 'Roboto Mono', monospace;
Положи, пожалуйста, стили текста в `Text`.

2020-04-25 22:41 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +    font-style: normal;
Это свойство by default.

2020-04-25 22:42 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +  const inputElement = useRef<HTMLInputElement>(null);
```suggestion
}: InputProps) => {
  const inputElement = useRef<HTMLInputElement>(null);
```

2020-04-25 22:44 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +          {addictionLine}
`addiction`?

2020-04-25 22:47 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +          onChange={event => {onChange(event.target.value);}}
Почитай, пожалуйста, про то, как [прокидывать коллбэки в React](https://reactjs.org/docs/faq-functions.html#arrow-function-in-render).

2020-04-25 22:50 UTC, avdotion commented on src/pitaya/components/Inputs/MonkeyButton.tsx
> +const MonkeyButton: React.FC<MonkeyButtonProps> = ({
В название компонентов не следует включать название его стиля, в приоритете функциональность. Например, можно назвать этот компонент ShowPasswordButton.

2020-04-25 22:51 UTC, avdotion commented on src/pitaya/components/Inputs/MonkeyButton.tsx
> +  console.log(memorizedOnClick);
```suggestion
```

2020-04-25 22:54 UTC, avdotion commented on src/pitaya/components/Inputs/Salt.tsx
> +  const[isTextHidden, changeTextHidden] = useState(true);
Следует типизировать хук `useState`.
А чтобы не выдумывать названия коллбека, предлагаю использовать нотацию [**state**, set**State**] = useState().

2020-04-25 23:13 UTC, avdotion commented on src/pitaya/components/Inputs/DomainName.tsx
> +  button={
Существует две проблемы здесь:
1. Идеологически иконка с обезьяной и кнопка PASTE не встречаются вместе, однако это явно разные сущности. Поэтому есть предложение разделить эту функциональность. Как аргумент предлагаю уточнить, что иконка с обезьяной встречается у инпутов типа `password`, а кнопка PASTE может возникнуть только в одном компоненте на странице.

2. В пропс `button` передается инстанцированный компонент. И он инстанцируется заново каждый раз, когда DomainName перерисовывается. Это большая проблема, предлагаю тебе самостоятельно изучить пути ее решения.

Отдельно хочется сказать, что в атомарной системе компонентов Pitaya есть задача уйти от таких сущностей как MasterPassword, Url и прочего, важно лишь, что существует Input с набором характеристик. Переразмечать логику следует, да, но
а) было бы здорово, чтобы информация о внешнем виде компонента располагалась только внутри этого компонента, а снаружи был бы достаточно ограниченый интерфейс,
б) для виджетов существуют отдельные представления, где можно наколхозить любые пропсы -- и неочевидно, зачем следует шарить представления виджетов: раз теперь MasterPassword лежит особняком от виджета, то все могут использовать представление (view) от MasterPassword, однако необходимости в этом нет.

2020-04-25 23:15 UTC, avdotion commented on src/pitaya/components/Inputs/DomainName.tsx
> +          color={[255, 255, 255, 1]}
На этом месте хочу обратить внимание, что Object в JS не является скалярным типом, и будет создаваться при каждом ре-рендере заново. Кроме того, давай зашарим цвета, чтобы не создавать копипасту и потом быстро перейти в дарк мод.

2020-04-25 23:17 UTC, avdotion commented on src/pitaya/components/Inputs/DomainName.tsx
> +  rightPadding='5px'
Не очень понятно, зачем это свойство выделено в отдельную пропсу. Давай воспользуемся здесь не кастомизацией, а темизацией.

2020-04-25 23:19 UTC, avdotion commented on src/pitaya/components/Inputs/DomainName.tsx
> +        background-color: #000000;
Минимум третий раз вижу, что цвет задается иным образом. Давай использовать какую-то конкретную палитру.

2020-04-25 23:20 UTC, avdotion commented on src/pitaya/components/Inputs/Input.tsx
> +  onChange: (value: string) => void,
Пропсы компонента делятся на две части, это мы уже обсуждали.

2020-04-25 23:22 UTC, avdotion commented on src/pitaya/components/Inputs/MonkeyButton.tsx
> +      onClick={() => {memorizedOnClick();}}
После прочтения статьи про коллбеки следует вернуться к этому месту.

2020-04-25 23:24 UTC, avdotion commented on src/ClueApp.tsx
> +          <MasterPassword
Возможно, путаница могла возникнуть в этом месте. В верстку рута ложатся не компоненты, а контентные виджеты инпутов. Именно поэтому я предлагаю не делать прослойку в виде отдельного представления для каждого инпута с отдельным набором пропсов

2020-04-25 23:25 UTC, avdotion commented on src/ClueApp.tsx
> +            buttonOnClick={() => {console.log('CLICK!');}}
😦

2020-04-25 23:28 UTC, avdotion commented on src/pitaya/components/Inputs/DomainName.tsx
> +  buttonOnClick,
К сожалению, не встретил кода, где из буфера достается текст.

2020-04-25 23:35 UTC, avdotion requested changes
Да, вторая ревизия сильно лучше предыдущей. Я не стал зацикливаться на двойных пробелах, пустых строчках и прочем, надеюсь ты это поправишь (или оно заедет в eslint правила). Нормально форматированный код читать приятнее.

Основные проблемы следующие:
* [x] Существуют несостыковки во внешнем виде
* [x] Существенно страдают нейминг и инкапсуляция
* [x] Заметны следы копипасты с предыдущей версии Clue, те решения, от которых мы решили отказаться в Pitaya
* [x] Текущей типизации недостаточно
* [x] Цвет не построен так, чтобы его можно было переключить одним ползунком потом

Если будут какие-либо вопросы по поводу моих комментариев, не стесняйся обращаться. Буду ждать скорейшие правки!

2020-04-26 09:25 UTC, killreal17 commented on src/pitaya/components/Text/index.tsx
> +|text {
Давай оставим это на следующий шаг, а пока сконцентрируемся на полях ввода.
Я уже завел issue https://github.com/avdotion/clue/issues/60

2020-04-29 16:38 UTC, killreal17 commented on src/pitaya/components/Inputs/Input.tsx
> +  |wrapper {
Исправлено

2020-04-29 16:38 UTC, killreal17 commented on src/pitaya/components/Inputs/Input.tsx
> +  }
Исправлено

2020-04-29 16:39 UTC, killreal17 commented on src/pitaya/components/Inputs/Input.tsx
> +  const inputElement = useRef<HTMLInputElement>(null);
Исправлено

2020-04-29 16:39 UTC, killreal17 commented on src/pitaya/components/Inputs/Input.tsx
> +          {addictionLine}
Исправлено

2020-04-29 16:40 UTC, killreal17 commented on src/pitaya/components/Text/index.tsx
> +  font-weight: 400;
Исправлено, но все же необходимо исправить ошибки в этом компоненте

2020-04-30 19:41 UTC, killreal17 commented on src/pitaya/components/Text/index.tsx
> +|text[use|theme='heading'] {
Следи за https://github.com/avdotion/clue/issues/60

2020-04-30 19:42 UTC, killreal17 commented on src/pitaya/components/Inputs/Input.tsx
> +    border: 1px solid black;
Надо завести отдельный issue, потому что это проблема встретится позже

2020-04-30 21:12 UTC, avdotion commented on src/components/Input.tsx
> +    cursor: pointer;
Ответа нет

2020-05-08 21:10 UTC, closed without merging